### ISSUE TITLE
Unexpected behavior for Get<T> on complex objects

### ISSUE THREAD

**Issue by gortok** [JasonPunyon/Rol#6]
I'm using the "Get this object if it exists, if not Create it" pattern, and one issue I'm seeing is when I get `Store.Get<T>` for a complex object, it'll return an object (with default values) even if that object doesn't exist in redis. Which I didn't expect because I thought it would use the redis `GET` command.

Here's the code:

```
public interface IA 
{
  string Id {get;}
  IB B {get; set;}
}

public interface IB
{
  IList<IC> C {get; set;}
}
```

And you can imagine what `IC` looks like. Anyway, when I try to get an object from Redis, I get an ArgumentNullException from Jil because `IA.B` is null; which I wouldn't have expected.

            var user = Store.Get<IA>("myIdNotInRedis");
            if (user.B == null) //throws exception here

> System.ArgumentNullException was unhandled
>   HResult=-2147467261
>   Message=Value cannot be null.
> Parameter name: text
>   Source=Jil
>   ParamName=text
>   StackTrace:
>        at Jil.JSON.Deserialize[T](String text, Options options) in C:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs:line 4751
>        at Rol.FromRedisValue`1.<>c.<Implement>b__1_3(RedisValue v, Store s)
>        at Rol.RedisOperations.GetHashValue[TKey,TValue](Store store, RedisKey hashName, TKey field)
>        at StackStats.Persistence.User.GetUser(String userId, String siteName) in c:\projects\shift\src\StatPersistence\Persistence\StackUser.cs:line 45
>        at XmlProcessor.BadgesProcessor.Process(XElement element, String siteName) in c:\projects\shift\src\XmlProcessor\BadgesProcessor.cs:line 34
>        at XmlProcessor.DocumentProcessor.processFile(IProcessor processor, XmlReader reader, String siteName) in c:\projects\shift\src\XmlProcessor\DocumentProcessor.cs:line 76
>        at XmlProcessor.DocumentProcessor.ProcessXmlDocument(String xmlFile) in c:\projects\shift\src\XmlProcessor\DocumentProcessor.cs:line 45
>        at StatRunner.Program.Main(String[] args) in c:\projects\shift\src\StatRunner\Program.cs:line 28
>   InnerException: 
>

**Comment by JasonPunyon** [comment]
Rol is trying to use Jil to deserialize IB because it doesn't have a get-only Id property. If you add the Id property the exception will go away.

**Comment by gortok** [comment]
@JasonPunyon  What's the 'right' way to GetOrCreate?  Even when I implement the Ids on all the dependent objects above; I still get an ArgumentNullException from Jil; here's what the code looks like:

```
public interface IA 
{
  string Id {get;}
  IB B {get; set;}
}

public interface IB
{
  int Id {get; }
  IList<IC> C {get; set;}
}

var user = Store.Get<IA>("User1"); //doesn't exist in redis yet.
if (user.B == null) {
  var b = new B();
  user.B = b;
}
//snip.. Later a calling method looks for this same object:

var user = Store.Get<IA>("User1"); //gets object from earlier. 
var c = new C();
if (user.B.C == null) {  //ArgumentNullException from Jil
  var ListIC = new List<IC>();
  user.B.C = ListIC; 
}
```


As a secondary issue; if I have custom getters (calculation fields for other properties), then should I be mapping what you return to my own object with that custom logic in the properties?  I assume I should; the same way I would with any Object Model.

**Comment by JasonPunyon** [comment]
What does IC look like?

**Comment by gortok** [comment]
```
public interface IC {
  int Id {get; }
  int Class {get;set; }
  string Name {get; set;}
  bool TagBased {get; set;}
  DateTime DateEarned {get; set;}
}
```

**Comment by JasonPunyon** [comment]
OK, it's the `IList<IC>` property on `IB` that's the problem. Jil doesn't know what to deserialize IList<T> into, therefore it dies.

**Comment by gortok** [comment]
Ah; so make it a List<T> or say fuck it and make it an array? (I remember that being an issue in JSON.NET a long time ago)

**Comment by JasonPunyon** [comment]
That would work. But you're JSON serializing the whole list into redis every time you want to make a change. If that's fine, then fine. If not, you can also look at the redis collections I expose (IRedisList, IRedisHash, IRedisSet, IRedisSortedSet, and IRedisHyperLogLog). If one of those expose the collections interface you want, you can use that for a bit more efficiency at single element interactions.

**Comment by gortok** [comment]
So to answer my own earlier question; mapping your objects to my Domain objects would be the 'right' way to separate any changes from taking effect immediately, or from having any accessors hit redis each time?

**Comment by JasonPunyon** [comment]
I don't know that I'd use this library that way (mapping to real domain objects in your code).

Part of the win of Rol (and the intended usage) is that you don't access anything in redis until you read or write a property on your object. This laziness keeps you from pulling down scads of unneeded data.

If you mean "mapping" like I think you do: If you were to pull an object from the store and map it to your domain object, you're going to access every property and do all those reads serially which will kill perf on the read (because I'm guessing whatever mapping you'd use wouldn't tap Rol's async support).

**Comment by gortok** [comment]
@JasonPunyon That makes sense.  Although if I have a property accessor that is purely a calculation field; then is that property ever stored with a value inside of Redis? If so; can I mark it in some way to keep Redis from storing its value?
interface IA {
  int Id {get;}
  string Name {get; set;}
  string FirstInitial {get;}
}
Class A: IA {
  int Id {get; private set}
  string Name {get; set;}
  string FirstInitial {
    return Name[0].ToUpper();
  }
}

**Comment by JasonPunyon** [comment]
This is one spot where things get interesting with using interfaces. My definition of the 'right' thing to do here (as of right now) is...

```c#
public interface IA 
{
    int Id { get; }
    string Name { get; set; }
}

public static class IAExtensions
{
    public static string FirstInitial(this IA ia) 
    {
        return ia.Name[0].ToUpper();
    }
}
```
